let buttonStart = document.querySelector("#start");
let buttonIncomPlus = document.querySelectorAll('button')[0];
let buttonExpensAdd = document.querySelectorAll('button')[1];
let depositCheck = document.querySelector("#deposit-check");
let additionalIncomeItem0 = document.querySelectorAll('.additional_income-item')[0];
let additionalIncomeItem1 = document.querySelectorAll('.additional_income-item')[1];
let resultTotalBudgetMonthValue = document.querySelector('.result-total budget_month-value');
let resultTotalBudgetDayValue = document.querySelector(".result-total budget_day-value");
let resultTotaExpensesMonthValue = document.querySelector(".result-total expenses_month-value");
let resultTotalAdditionalIncomeValue = document.querySelector(".result-total additional_income-value");
let resultTotalAdditionalExpensesValue = document.querySelector(".result-total additional_expenses-value");
let resultTotalIncomePeriodValue = document.querySelector(".result-total income_period-value");
let resultTotalTargetMonthValue = document.querySelector(".result-total target_month-value");
let periodSelect = document.querySelector('.period-select')
